name: test

on:
  push:
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64]

    steps:
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - uses: actions/checkout@master
      with:
        # otherwise, you will failed to push refs to dest repo
        fetch-depth: 0

    - name: Install alcor
      run: |
        pip install git+https://github.com/UrsaAlcor/mocli.git
        alcor init "$(pwd)/aclor"
        alcor activate --auto

    - name: Install linker
      run: |
        source /home/runner/.config/mocli/bashrc
        activate_alcor 

        alcor install linker --url https://github.com/UrsaAlcor/linker/releases/download/v0.0.1/linker_x86_64.zip
        module load linker
        gcc tests/linker_main.c -o linker_main -llinker
